x-airflow-common: &airflow-common
  image: engine-airflow-custom:latest
  env_file: secrets.env
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow    
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
    AIRFLOW__CORE__TEST_CONNECTION: "Enabled"
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth"
  volumes:
    - airflow-data:/opt/airflow
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins    
    - ./datasets:/opt/airflow/datasets    
    - ./dbt:/home/airflow/dbt
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    postgres:
      condition: service_healthy
  networks:
    - airflow-network

services:

  postgres:
    image: postgres:latest
    container_name: engine_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - airflow-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: engine_pgadmin_ui
    environment:
      PGADMIN_DEFAULT_EMAIL: engine@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - airflow-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin 

  airflow-webserver:
    <<: *airflow-common
    command: >
      bash -c "
      airflow db init &&
      airflow db migrate &&
      airflow webserver
      "
    ports:
      - "8080:8080"
      - "8100:8100"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080/health"]
      interval: 10s
      timeout: 30s
      retries: 5

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler

  airflow-worker:
    <<: *airflow-common
    command: celery worker
    environment:
      <<: *airflow-common-env
      DUMB_INIT_SETSID: "0"

  airflow-init:
    <<: *airflow-common
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
    command: >
      bash -c "
      airflow db init &&
      airflow db migrate &&
      airflow users create --username admin --firstname Mohamed --lastname Nasr --role Admin --email admin@admin.com --password admin
      "

volumes:
  postgres-data:
  airflow-data:
  pgadmin-data:

networks:
  airflow-network:
    driver: bridge